# Server
server:
  port: 8080

# Application Configuration
appConfigs:
  oauth:
    clientId: client
    clientSecret: secret
    grandTypes:
      - password
      - authorization_code
      - refresh_token
      - implicit
    scopes:
      - read
      - write
      - trust
    accessTokenValiditySeconds: 600
    refreshTokenValiditySeconds: 1200
    resourceId: resource_id
  cors:
    enabled: false
    pathPattern: /api/**
    allowedOrigins:
      - http://localhost:8686
      - http://localhost:8787
    allowedMethods:
      - DELETE
      - GET
      - POST
      - PUT
    exposedHeaders:
      - Authorization
    allowCredentials: true
